### PR TITLE
Remove import from the code in order to be able to bundle and minify the module

### PR DESCRIPTION
**Pull request by ricardomozartlino**
In order to be able to bundle our code, we should directly specify the imports otherwise the plugin will not recognize the import

Is there a problem to change it?

### CODE REVIEW

**Comment by ricardomozartlino** [comment]
Yeh, makes sense. Done!

**Comment by BryanDonovan** [comment]
Thanks.  I'll get this merged asap.

**Comment by BryanDonovan** [comment]
released in 3.6.3

**Comment by ricardomozartlino** [comment]
Thank you

**Pull request merged**
