### PR TITLE
Add explicit return in wrapPromise.

### LINKED ISSUE #108: New warning on upgrade to bluebird 3.5.1
I recently upgraded to bluebird 3.5.1 and am now seeing a lot of the following warnings in my logs:

```
(node:19) Warning: a promise was created in a handler at app/node_modules/cache-manager/lib/caching.js:52:21 but was not returned from it, see http://goo.gl/rRqMUw 
at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
```

I believe adding an explicit `return` to `caching.js:52` would remove the warning, i.e.:

```js
return cb(null, result);
```

Thanks!

### PR DESCRIPTION
**Pull request by jeff-kilbride**
Fixes #108.

### CODE REVIEW

**Comment by BryanDonovan** [comment]
Thanks!

**Comment by BryanDonovan** [comment]
Merged in version 2.5.0

**Comment by jeff-kilbride** [comment]
Hi Brian,

I see you updated `package.json` to 2.5.0 in github, but npm still has 2.4.0. Is 2.5.0 ready to release or will it be a while, yet?

Thanks!

**Comment by BryanDonovan** [comment]
Oops, I thought I had published it. It's available now.

**Pull request merged**
