### PR TITLE
Using lodash.clonedeep instead of lodash to decrease the module size

### PR DESCRIPTION
**Pull request by ricardomozartlino**
By using lodash.clonedeep we do not need to import the entire lodash module, only a specific function 

This will help us on keeping our serverless project small.

Thank you

### CODE REVIEW

**Comment by cnovais** [comment]
Yes, I agree with @ricardomozartlino 

If we had the option of importing a specific function it would make our project small.

**Review by cnovais — APPROVED** [review]

**Comment by BryanDonovan** [comment]
Thanks!

**Comment by ricardomozartlino** [comment]
@BryanDonovan, I think we merged it to the develop branch, my bad!

**Comment by BryanDonovan** [comment]
@ricardomozartlino - no, I changed it to develop.  I use `git-flow` which uses a `develop` branch by default.  I'll have it merged and released soon.

**Comment by BryanDonovan** [comment]
This is available in 3.6.2

**Comment by ricardomozartlino** [comment]
Thank you!

**Pull request merged**
