### PR TITLE
fix: ttl not working

### PR DESCRIPTION
**Pull request by anchan828**
Hi, I upgraded to cache-manager@4.0.0 and TTL was not working.

Perhaps it was an omission in #193 updates.

* In lru-cache@7.x, `maxAge` was renamed to `ttl`.
* The `set()` function takes options objects instead of ttl integer.

See: https://github.com/isaacs/node-lru-cache/blob/main/CHANGELOG.md#specific-api-changes

## Versions

cache-manager: 4.0.0
lru-cache: 7.10.1
node: 18.2.0
npm: 8.9.0

### CODE REVIEW

**Comment by anchan828** [comment]
The some tests are failing, so I will fix them.

**Comment by anchan828** [comment]
Test passed😀
4ea193e16177d087dd0cc4a6955e8928

**Comment by BryanDonovan** [comment]
Thanks.  I'll get this merged ASAP.

**Comment by BryanDonovan** [comment]
this is available in version 4.0.1

**Comment by taoliujun** [comment]
Thanks. I discover that cache get data was `undefined` a few days ago and i don't know why. I must fix this problem because app should be deploy today and i found `ttl` param was lost in lru which reason is it accept object options but not number.

Thanks your merge request!!!

**Pull request merged**
