### PR TITLE
memoryStore 增加set方法的ttl

### PR DESCRIPTION
**Pull request by zhudan**
memoryStore.set() 增加 maxAge参数

### CODE REVIEW

**Comment by BryanDonovan** [comment]
I merged this, but I made a change: the `options.ttl` in memory store's `set` function gets multiplied by 1000 to convert to seconds.

**Comment by zhudan** [comment]
can you publish this version to NPM? I want it.

**Comment by zhudan** [comment]
3Q

**Comment by BryanDonovan** [comment]
I think I published it in 1.1.0. I'm away from my computer right now but I can check later.

**Comment by zhudan** [comment]
on npm, the latest version still is 1.0.0, wait your upgrading， thank you！ yoyo~ check now~

**Comment by BryanDonovan** [comment]
Hi, this is published in 1.1.0 now. Sorry about that.

**Pull request merged**
